### ISSUE TITLE
Image import

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub#24]
![picture](https://user-images.githubusercontent.com/13540669/48131502-48511a00-e2b6-11e8-9498-cb0d6344f27e.png)

**Comment by curran** [comment]
Image import may be cool, but it feels out of scope for the project.

A workaround would be to host the image elsewhere, for example in GitHbu issues like this, and then use an image tag like this:

```html
<img src="https://user-images.githubusercontent.com/13540669/48131502-48511a00-e2b6-11e8-9498-cb0d6344f27e.png">
```
