### ISSUE TITLE
"An unexpected error has occurred." when logging in

### ISSUE THREAD

**Issue by JulianWgs** [datavis-tech/vizhub#76]
When I login with my Github Account the website displays "An unexpected error has occurred." with this URL:
```
https://vizhub.com/auth/github?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch
```
(Please tell me if there is anything confidential in that link)

After that Im logged into Github.

Im using Firefox 69.0 for Ubuntu.

Thanks in advance!

**Comment by curran** [comment]
I see the problem. It should be working now. Can you please try again?

**Comment by curran** [comment]
Thanks for reporting this. Confirming I can reproduce the problem. Investigating now.

**Comment by JulianWgs** [comment]
Now Im getting 404 error 

(I also get performance spikes, but I dont know if thats a problem on my machine. Never happened before when visiting Vizhub.)

Oh thank you for your great d3 tutorial!! Im following along and it has been great so far :)

**Comment by curran** [comment]
I'm messing around right now with the authentication callback URL, which I accidentally messed up when I recovered VizHub from an outage recently. Hoping to get it right soon!

**Comment by curran** [comment]
OK It's working again. Phew!

I invite you to try VizHub 2.0 beta, which you can get to by adding "beta." to the beginning of the URL of any Viz.

Happy to hear you're following the D3 tutorial!

**Comment by curran** [comment]
Closing this. Feel free to re-open if the error occurs again.

**Comment by JulianWgs** [comment]
Thank you for the fast support! It works now :)
